### PR TITLE
Update lib.rs

### PR DESCRIPTION
**Pull request by chickoocoutinho**
Added "style: width 100%" in image tags for better compatibility while using in email clients.

### CODE REVIEW

**Comment by yujixr** [comment]
It’s cool!
I’ll deploy this next weekend.

**Comment by chickoocoutinho** [comment]
There is another img tag in the code(lib.rs) , should I make a pull request and add "style: 100%" to that too?

**Comment by yujixr** [comment]
You don’t have to. I’ll do it at the time of deployment.

**Comment by yujixr** [comment]
I deployed this patch. (and I added inline css to another img tag)

Thank you for contributing!

**Pull request merged**
